# Generated by Django 3.0.1 on 2020-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0002_auto_20191220_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="expected_files_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
