# Generated by Django 3.0.4 on 2020-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0005_auto_20201215_1517"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("parent", "transform_type"), name="unique_upgraded_compiled_collection"
            ),
        ),
    ]
