# Generated by Django 3.0.4 on 2021-01-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0007_auto_20210115_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="data_type",
            field=models.TextField(blank=True, choices=[("releases", "Releases"), ("records", "Records")], null=True),
        ),
    ]
