# Generated by Django 3.0.4 on 2021-01-21 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0008_collection_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="data_type",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
