# Generated by Django 3.0.4 on 2021-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_auto_20210121_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='compilation_started',
            field=models.BooleanField(default=False),
        ),
    ]
