# Generated by Django 3.0.4 on 2021-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0011_collectionnote_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionfilestep",
            name="name",
            field=models.TextField(
                blank=True, choices=[("UPGRADE", "Upgrade"), ("COMPILE", "Compile"), ("CHECK", "Check")]
            ),
        ),
    ]
