# Generated by Django 3.0.4 on 2021-02-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0014_auto_20210216_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingstep",
            name="collection",
            field=models.ForeignKey(
                db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to="process.Collection"
            ),
            preserve_default=False,
        ),
    ]
