# Generated by Django 3.0.4 on 2021-02-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0016_auto_20210217_1233"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processingstep",
            name="unique_collection_file_item_name",
        ),
    ]
