# Generated by Django 3.0.4 on 2021-03-24 16:15

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0019_auto_20210217_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionnote",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
