# Generated by Django 3.0.4 on 2021-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0020_collectionfile_filepath'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collectionfile',
            name='unique_collection_file_identifiers',
        ),
        migrations.AddConstraint(
            model_name='collectionfile',
            constraint=models.UniqueConstraint(fields=('collection', 'filepath'), name='unique_collection_file_identifiers'),
        ),
    ]
