# Generated by Django 3.2 on 2021-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0022_auto_20210510_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
