# Generated by Django 3.2 on 2021-08-19 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0023_collection_completed_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectionnote",
            name="unique_collection_note_identifiers",
        ),
    ]
