# Generated by Django 3.2.11 on 2022-02-08 20:27

from django.db import migrations, models
import simplejson.encoder


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0024_remove_collectionnote_unique_collection_note_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionnote",
            name="data",
            field=models.JSONField(blank=True, encoder=simplejson.encoder.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="data",
            field=models.JSONField(encoder=simplejson.encoder.JSONEncoder),
        ),
        migrations.AlterField(
            model_name="packagedata",
            name="data",
            field=models.JSONField(encoder=simplejson.encoder.JSONEncoder),
        ),
    ]
