# Generated by Django 3.2.11 on 2022-01-31 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0024_remove_collectionnote_unique_collection_note_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionfile",
            name="collection",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_files",
                to="process.collection",
            ),
        ),
    ]
