# Generated by Django 3.2.13 on 2022-06-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0025_auto_20220208_2027"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="check_older_data_with_schema_version_1_1",
        ),
    ]
