# Generated by Django 3.2.13 on 2022-06-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0026_remove_collection_check_older_data_with_schema_version_1_1"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="release",
            name="release_collection_id_idx",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="check_data",
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["collection"], name="release_collection_id_idx"),
        ),
    ]
