# Generated by Django 3.2.13 on 2022-09-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0027_auto_20220608_1851"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(fields=("collection", "ocid"), name="unique_record_identifiers"),
        ),
    ]
