# Generated by Django 4.2.2 on 2023-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0028_record_unique_record_identifiers"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collection",
            name="unique_collection_identifiers",
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transform_type", "")),
                fields=("source_id", "data_version", "sample"),
                name="unique_collection_identifiers",
                violation_error_message="A matching collection already exists.",
            ),
        ),
    ]
