# Generated by Django 4.2.2 on 2023-07-04 03:55

import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0029_remove_collection_unique_collection_identifiers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionfile",
            name="errors",
        ),
        migrations.RemoveField(
            model_name="collectionfile",
            name="warnings",
        ),
        migrations.RemoveField(
            model_name="collectionfileitem",
            name="errors",
        ),
        migrations.RemoveField(
            model_name="collectionfileitem",
            name="warnings",
        ),
        migrations.AlterField(
            model_name="collection",
            name="data_type",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="collection",
            name="steps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="collectionnote",
            name="data",
            field=models.JSONField(blank=True, default=dict, encoder=simplejson.encoder.JSONEncoder),
        ),
    ]
