# Generated by Django 4.2.2 on 2023-07-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0030_remove_collectionfile_errors_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recordcheck",
            name="unique_record_check_record_id_and_more",
        ),
        migrations.RemoveConstraint(
            model_name="releasecheck",
            name="unique_release_check_release_id_and_more",
        ),
        migrations.RemoveField(
            model_name="recordcheck",
            name="override_schema_version",
        ),
        migrations.RemoveField(
            model_name="releasecheck",
            name="override_schema_version",
        ),
        migrations.AddConstraint(
            model_name="recordcheck",
            constraint=models.UniqueConstraint(fields=("record",), name="unique_record_check_record_id_and_more"),
        ),
        migrations.AddConstraint(
            model_name="releasecheck",
            constraint=models.UniqueConstraint(fields=("release",), name="unique_release_check_release_id_and_more"),
        ),
    ]
