# Generated by Django 4.2.2 on 2023-07-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0031_remove_recordcheck_unique_record_check_record_id_and_more_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recordcheck",
            name="unique_record_check_record_id_and_more",
        ),
        migrations.RemoveConstraint(
            model_name="releasecheck",
            name="unique_release_check_release_id_and_more",
        ),
        migrations.RemoveIndex(
            model_name="recordcheck",
            name="record_check_record_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="releasecheck",
            name="release_check_release_id_idx",
        ),
        migrations.AlterField(
            model_name="recordcheck",
            name="record",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="process.record"),
        ),
        migrations.AlterField(
            model_name="releasecheck",
            name="release",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="process.release"),
        ),
    ]
