# Generated by Django 4.2.10 on 2024-04-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0032_remove_recordcheck_unique_record_check_record_id_and_more_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="scrapyd_job",
            field=models.TextField(blank=True),
        ),
    ]
