# Generated by Django 4.2.11 on 2024-04-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0033_collection_scrapyd_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="data_version",
            field=models.DateTimeField(help_text="The time at which the files were retrieved (not loaded)."),
        ),
        migrations.AlterField(
            model_name="processingstep",
            name="name",
            field=models.TextField(
                choices=[("LOAD", "Load"), ("COMPILE", "Compile"), ("CHECK", "Check")], db_index=True
            ),
        ),
    ]
