# Generated by Django 4.2.11 on 2024-04-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0034_alter_collection_data_version_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="processingstep",
            name="processing_step_collection_file_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="processingstep",
            name="processing_step_ocid_idx",
        ),
        migrations.RemoveIndex(
            model_name="processingstep",
            name="processing_step_name_idx",
        ),
        migrations.AlterField(
            model_name="processingstep",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="processing_steps", to="process.collection"
            ),
        ),
        migrations.AlterField(
            model_name="processingstep",
            name="name",
            field=models.TextField(choices=[("LOAD", "Load"), ("COMPILE", "Compile"), ("CHECK", "Check")]),
        ),
        migrations.AlterField(
            model_name="processingstep",
            name="ocid",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
