# Generated by Django 4.2.11 on 2024-04-18 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0036_remove_compiledrelease_compiled_release_ocid_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_record_identifiers",
        ),
    ]
