# Generated by Django 4.2.11 on 2024-06-11 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0037_remove_record_unique_record_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="source_id",
            field=models.TextField(
                help_text="If sourced from Scrapy, this should be the name of the spider.",
                validators=[
                    django.core.validators.RegexValidator(
                        "^([a-z]+_)*[a-z]+$", "source_id must be letters and underscores only"
                    )
                ],
            ),
        ),
    ]
