# Generated by Django 4.2.11 on 2024-07-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0038_alter_collection_source_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingstep",
            name="collection",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_steps",
                to="process.collection",
            ),
        ),
        migrations.AddIndex(
            model_name="processingstep",
            index=models.Index(fields=["collection", "name", "ocid"], name="processing_step_collection_id_ocid_idx"),
        ),
    ]
