# Generated by Django 4.2.15 on 2024-10-03 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0039_alter_processingstep_collection_and_more"),
    ]

    operations = [migrations.RunSQL("CREATE INDEX data_data_date_idx ON data((data->>'date'))")]
