# Generated by Django 4.2.15 on 2024-10-07 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0040_auto_20241003_1605"),
    ]

    operations = [migrations.RunSQL("DROP INDEX data_data_date_idx")]
