# Generated by Django 4.2.15 on 2024-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0041_auto_20241007_0357"),
    ]

    operations = [
        migrations.AddField(
            model_name="compiledrelease",
            name="release_date",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="release",
            name="release_date",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            """
            UPDATE release
            SET release_date = COALESCE(data ->> 'date', '')
            FROM data
            WHERE data_id = data.id
            """
        ),
        migrations.RunSQL(
            """
            UPDATE compiled_release
            SET release_date = COALESCE(data ->> 'date', '')
            FROM data
            WHERE data_id = data.id
            """
        ),
    ]
