# Generated by Django 4.2.16 on 2024-11-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0043_compiledrelease_collection_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionfileitem",
            name="collection_file",
        ),
        migrations.RemoveIndex(
            model_name="compiledrelease",
            name="compiled_release_collection_file_item_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="record",
            name="record_collection_file_item_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="release",
            name="release_collection_file_item_id_idx",
        ),
        migrations.RemoveField(
            model_name="compiledrelease",
            name="collection_file_item",
        ),
        migrations.RemoveField(
            model_name="record",
            name="collection_file_item",
        ),
        migrations.RemoveField(
            model_name="release",
            name="collection_file_item",
        ),
        migrations.AlterField(
            model_name="compiledrelease",
            name="collection_file",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.CASCADE, to="process.collectionfile"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="collection_file",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.CASCADE, to="process.collectionfile"
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="collection_file",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.CASCADE, to="process.collectionfile"
            ),
        ),
        migrations.DeleteModel(
            name="CollectionFileItem",
        ),
    ]
