# Generated by Django 4.2.22 on 2025-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0044_remove_collectionfileitem_collection_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionfile",
            name="compilation_started",
            field=models.BooleanField(default=False),
        ),
    ]
