# Generated by Django 5.2.12 on 2026-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0045_collectionfile_compilation_started"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="collection",
            name="unique_collection_identifiers",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transform_type", "")),
                fields=("source_id", "data_version", "sample"),
                name="unique_collection_identifiers",
                violation_error_code="unique_collection",
                violation_error_message="A matching collection already exists.",
            ),
        ),
    ]
