# Generated by Django 5.2.12 on 2026-06-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0046_alter_collection_unique_collection_identifiers"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="data",
            name="unique_data_hash_md5",
        ),
        migrations.RemoveConstraint(
            model_name="packagedata",
            name="unique_package_data_hash_md5",
        ),
        migrations.AddConstraint(
            model_name="data",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hash_md5", ""), _negated=True), fields=("hash_md5",), name="unique_data_hash_md5"
            ),
        ),
        migrations.AddConstraint(
            model_name="packagedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hash_md5", ""), _negated=True),
                fields=("hash_md5",),
                name="unique_package_data_hash_md5",
            ),
        ),
    ]
