# Generated by Django 5.2.12 on 2026-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    # Building the index with CREATE INDEX CONCURRENTLY avoids holding an ACCESS EXCLUSIVE lock on the large `release`
    # table for the duration of the build. This requires the migration to not run in a transaction. If a build fails,
    # it leaves an INVALID index, which must be dropped manually before re-running.
    atomic = False

    dependencies = [
        ("process", "0047_remove_data_unique_data_hash_md5_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="release",
                    name="release_collect_4cb073_idx",
                ),
                migrations.AddIndex(
                    model_name="release",
                    index=models.Index(
                        fields=["collection", "ocid", "release_date"], name="release_collect_ca3472_idx"
                    ),
                ),
            ],
            database_operations=[
                # Create the new index before dropping the old one, so a usable index is always available.
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY "release_collect_ca3472_idx" '
                    'ON "release" ("collection_id", "ocid", "release_date")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "release_collect_ca3472_idx"',
                ),
                migrations.RunSQL(
                    sql='DROP INDEX CONCURRENTLY IF EXISTS "release_collect_4cb073_idx"',
                    reverse_sql='CREATE INDEX CONCURRENTLY "release_collect_4cb073_idx" '
                    'ON "release" ("collection_id", "ocid")',
                ),
            ],
        ),
    ]
