# Generated by Django 5.2.12 on 2026-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0048_remove_release_release_collect_4cb073_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="compilation_enqueued",
            field=models.BooleanField(default=False),
        ),
    ]
