name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: write
      # libcoveocds is optional (try-except block).
      standard-maintenance-scripts-ignore: libcoveocds
      standard-maintenance-scripts-files: requirements_nongpl.in
